name: Code formatting

on:
  pull_request:
    branches: [ master ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
        with:
          ref: ${{ github.head_ref }}
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
