name: Code formatting

on:
  pull_request:
    branches: [ master ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        shell: bash
        run: echo ${GITHUB_HEAD_REF}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF})"
        id: extract_branch
      - uses: actions/checkout@v2 # v2 minimum required
        with:
          ref: ${GITHUB_HEAD_REF}
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
