# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI build & test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildAndTestJava8-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and test with Maven
      run: mvn -B package --file Project/pom.xml --define testrunparams=


  buildAndTestJava11-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and test with Maven
      run: mvn -B package --file Project/pom.xml --define testrunparams='--illegal-access=deny --add-opens java.desktop/java.awt=ALL-UNNAMED'


  buildAndTestJava17-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build and test with Maven
      run: mvn -B package --file Project/pom.xml --define testrunparams=' --add-opens java.desktop/java.awt=ALL-UNNAMED'


  buildAndTestJava8-windows:
    runs-on: windows-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and test with Maven
      run: mvn -B package --file Project/pom.xml --define testrunparams=


  buildAndTestJava11-windows:
    runs-on: windows-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and test with Maven
      run: mvn -B package --file Project/pom.xml --define testrunparams="--illegal-access=deny --add-opens java.desktop/java.awt=ALL-UNNAMED"


  buildAndTestJava17-windows:
    runs-on: windows-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build and test with Maven
      run: mvn -B package --file Project/pom.xml --define testrunparams=" --add-opens java.desktop/java.awt=ALL-UNNAMED"
